# Generated by Django 2.1 on 2018-08-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=5)),
                ('num_bathrooms', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('num_bedrooms', models.IntegerField(default=0)),
                ('home_size', models.IntegerField(default=0)),
                ('home_type', models.CharField(max_length=25)),
                ('last_sold_date', models.DateField()),
                ('last_sold_price', models.IntegerField(default=0)),
                ('link', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=5)),
                ('property_size', models.IntegerField(default=0)),
                ('rent_price', models.CharField(max_length=5)),
                ('rentzestimate_amount', models.IntegerField(default=0)),
                ('rentzestimate_last_updated', models.DateField()),
                ('tax_value', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('tax_year', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('zestimate_amount', models.IntegerField(default=0)),
                ('zestimate_last_updated', models.DateField()),
                ('zillow_id', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
    ]
