# Generated by Django 2.1 on 2018-08-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='last_sold_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='rentzestimate_last_updated',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='house',
            name='zestimate_last_updated',
            field=models.CharField(max_length=10),
        ),
    ]
